[versions]
jetbrains-compose = "1.2.0"
kotlin = "1.7.10"

[libraries]
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core" }
kobweb-silk-core = { module = "com.varabyte.kobweb:kobweb-silk" }
kobweb-silk-icons-fa = { module = "com.varabyte.kobweb:kobweb-silk-icons-fa" }

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kobweb-application = { id = "com.varabyte.kobweb.application" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
