[versions]
jetbrains-compose = "1.5.1"
kotlin = "1.9.10"

[libraries]
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core" }
kobweb-silk = { module = "com.varabyte.kobweb:kobweb-silk" }
silk-icons-fa = { module = "com.varabyte.kobwebx:silk-icons-fa" }

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kobweb-application = { id = "com.varabyte.kobweb.application" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
