[versions]
jetbrains-compose = "1.6.0"
kotlin = "1.9.22"
kotlinx-serialization = "1.6.3"

[libraries]
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core" }
kobweb-silk = { module = "com.varabyte.kobweb:kobweb-silk" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
silk-icons-fa = { module = "com.varabyte.kobwebx:silk-icons-fa" }

[plugins]
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
kobweb-application = { id = "com.varabyte.kobweb.application" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
